### PR TITLE
Added pip

### PR DESCRIPTION
**Pull request by iBobik**

### CODE REVIEW

**Comment by master-bob** [comment]
Hey-o,

What's the benefit of adding pip? Is it used in building android stuff?

**Comment by iBobik** [comment]
A lot of automations use Python. I guess the same reason why you included Node and it's NPM. :-)Honza Pobořil💬Signal9. 2. 2023 v 19:26, Leonardo Canessa ***@***.***>:﻿
Hey-o,
What's the benefit of adding pip? Is it used in building android stuff?

**Comment by master-bob** [comment]
Mate, I'm not the maintainer. I don't know why Node and NPM are included.

**Comment by mingchen** [comment]
@iBobik Thank you for your contribution.

**Pull request merged**
